const mongoose = require('mongoose');
var tree = require('../middleware/model-tree');
var {slugGenerator} = require('../middleware/mongooge-slug-generator');
// Article Schema
const objSchema = mongoose.Schema({
  category_id: {
    type: String,
  },
  author: {
    type: String,
    required: true
  },
  title: {
    type: String,
    required: true
  },
  body: {
    type: String,
    required: true
  },
  urlAudioService:{
    type: String,
  },
  createAt:{
    type:Date,
    immutable:true,
    default:()=> Date.now()
  },
  updateAt:{
    type:Date,
    default:()=> Date.now()
  },
  status:{
    type:Boolean,
    default:false
  }
});


objSchema.plugin(tree,{
  pathSeparator : '#',              // Default path separator
  onDelete :      'DELETE',       // Can be set to 'DELETE' or 'REPARENT'. Default: 'REPARENT'
  numWorkers:     5,                // Number of stream workers
  idType:         objSchema._id  // Type used for _id. Can be, for example, String generated by shortid module
});

objSchema.plugin(slugGenerator);

const Article = mongoose.model('Article', objSchema);

module.exports.Article = Article;
